#!/usr/bin/env bash
#
# Summary: Configure the system for rivian-usb (background service, mounts, etc.)
#
# This command is effectively an alias, as is `riv self-update`, to provide a
# stable interface for in-place upgrades across versions. For more flexibility,
# see `riv help install`.
#
# Usage: riv self-install

exec riv install -i -t "$_RIV_ROOT"
