#!/usr/bin/env bash
#
# Summary: Prepare to build a rivian-usb image
#
# Usage: riv image-prepare <path/to/repo>
#
# Examples:
#   riv image-prepare rivian-usb

source "${_RIV_SHARE}/riv/lib/main.bash" || exit 1

## Check script dependencies

__require_dependencies git rsync

## Set defaults

REPO_PATH=

## Define functions

function handle_arguments() {
  REPO_PATH="$1"
}

function main() {
  __say "Preparing the image build environment..."

  local PI_GEN_DIR="image/pi-gen"
  local INSTALL_STAGE_DIR="stage3/99-install-rivian-usb"
  local RIV_FILES_DIR="${INSTALL_STAGE_DIR}/files/riv"

  cd "$REPO_PATH" || return 1

  __say "Initializing ${PI_GEN_DIR}..."
  git submodule deinit -f "$PI_GEN_DIR" >/dev/null
  git submodule update --init "$PI_GEN_DIR" >/dev/null 2>&1

  cd "$PI_GEN_DIR" || return 1

  __say "Configuring pi-gen..."
  cp ../config ./config

  __say "Installing customizations..."
  # skip default pi-gen image generation
  touch stage{0..2}/SKIP_IMAGES
  rm -rf stage{3..5}
  # copy our custom stage
  rsync -a --delete ../customizations/ stage3/
  # copy the standard pi-gen prerun script
  cp stage2/prerun.sh stage3/prerun.sh
  # list package dependencies for installation
  riv dependencies -p > "${INSTALL_STAGE_DIR}/00-packages"

  __say "Installing \`riv\`..."
  mkdir -p "$RIV_FILES_DIR"
  riv install -s "../.." -t "$RIV_FILES_DIR" >/dev/null

  __say "Done"
}

function validate_input() {
  __validate_present "$REPO_PATH" "Repository path not speficied. See \`riv help $_RIV_COMMAND\`."

  test -d "${REPO_PATH}/.git" || __die "Not a git repository: ${REPO_PATH}"
}
