#!/usr/bin/env bash
#
# Summary: List commands and their descriptions
#
# Usage: riv commands
#
# Options:
#   -s Short output; command names only
#
# Examples:
#   List commands and summaries:
#     riv commands

set -e

SUMMARIES=1

for arg in "$@"; do
  if [[ "$arg" == "-s" ]]; then
    SUMMARIES=
    shift
  fi
done

shopt -s nullglob

if [[ -n "$SUMMARIES" ]]; then
  echo -e 'See `riv help <command>` to read about a specific subcommand\n'

  riv-help --commands | sed 's/^/  /'
else
  for DIR in ${PATH//:/$'\n'}; do
    for CMD in "${DIR}/riv-"*; do
      echo "${CMD##*riv-}"
    done
  done | sort | uniq
fi
