#!/usr/bin/env bash
#
# Summary: Print `riv` dependencies
#
# Usage: riv dependencies [opts]
#
# Options:
#   -b Print binary names only
#   -p Print package names only
#
# Examples:
#   Show `riv` dependencies in '[binary:]package' format
#     riv dependencies
#   Show `riv` dependency package names
#     riv dependencies -p

source "${_RIV_SHARE}/riv/lib/main.bash" || exit 1

## Check script dependencies

__require_dependencies cat cut grep sed

## Set defaults

BINARY_ONLY=
PACKAGE_ONLY=

## Define functions

function main() {
  local DEPS=$(
    sed -re 's/\s*#.*//' "${_RIV_SHARE}/riv/dependencies.txt" |
    grep -vE '^\s*$'
  )

  echo "$DEPS" |
  if [[ "$BINARY_ONLY" ]]; then
    cut -d : -f 1
  elif [[ "$PACKAGE_ONLY" ]]; then
    cut -d : -f 2
  else
    cat -
  fi | grep -v '^$' | sort | uniq
}

function handle_options() {
  case "$1" in
    -) export RIV_OPTIONS=":bp";;
    b) BINARY_ONLY=1;;
    p) PACKAGE_ONLY=1;;
  esac
}

function validate_input() {
  __validate_exclusive "$BINARY_ONLY" "$PACKAGE_ONLY" ||
    __die "Specify -b or -p, but not both"
}
