#!/usr/bin/env bash
#
# Summary: Prepare to build a rivian-usb image
#
# Usage: riv image-prepare <path/to/repo>
#
# Examples:
#     riv image-prepare rivian-usb

source "${_RIV_SHARE}/riv-stdlib.bash" || exit 1

## Check script dependencies

_require_dependencies git rsync

## Set defaults

REPO_PATH=

## Define functions

function parse_options() {
  REPO_PATH="$1"
}

function prepare() {
  _say "Preparing the image build environment..."

  local PI_GEN_DIR="image/pi-gen"
  local INSTALL_STAGE_DIR=customizations/99-install-rivian-usb
  local RIV_FILES_DIR="${INSTALL_STAGE_DIR}/files/riv"

  cd "$REPO_PATH" || return 1

  _say "Initializing ${PI_GEN_DIR}..."
  git submodule deinit -f "$PI_GEN_DIR" >/dev/null
  git submodule update --init "$PI_GEN_DIR" >/dev/null 2>&1

  cd "$PI_GEN_DIR" || return 1

  _say "Configuring pi-gen..."
  cp ../config ./config

  _say "Installing customizations..."
  # skip default pi-gen image generation
  touch stage{0..5}/SKIP_IMAGES
  # copy our custom stage
  rsync -a --delete ../customizations/ customizations/
  # copy the standard pi-gen prerun script
  cp stage2/prerun.sh customizations/prerun.sh
  # list package dependencies for installation
  riv dependencies -p > "${INSTALL_STAGE_DIR}/00-packages"

  _say "Installing \`riv\`..."
  mkdir -p "$RIV_FILES_DIR"
  riv install -s "../.." -t "$RIV_FILES_DIR" >/dev/null

  _say "Done"
}

function validate_input() {
  _validate_present "$REPO_PATH" "Repository path not speficied. See \`riv help $_RIV_COMMAND\`."

  test -d "${REPO_PATH}/.git" || _error "Not a git repository: ${REPO_PATH}"
}

## Run the script

parse_options "$@" &&
validate_input &&
prepare
