#!/usr/bin/env bash
#
# Summary: Display the `riv` version
#
# Usage: riv version [opts]
#        riv --version [opts]
#
# Options:
#   -l Print the longer version

set -e

VERSION=${_RIV_VERSION:-dev}

if [[ "$1" == "-l" ]]; then
  echo "Rivian-USB ${VERSION}"
else
  echo "$VERSION"
fi
