#!/usr/bin/env bash
#
# Summary: Display the `riv` version
#
# Usage: riv version [opts]
#        riv --version [opts]
#
# Options:
#   -l Print the longer version

set -e

if [[ "$1" == "-l" ]]; then
  echo -n "Rivian-USB version: "
fi

echo "${_RIV_VERSION:dev}"

if [[ "$1" == "-l" ]]; then
  echo "https://github.com/rivian-community/rivian-usb"
fi
