#!/usr/bin/env bash
#
# Summary: Remount filesystems as read-write
#
# Usage: riv util-remount [path...]
#
# Examples:
#   Remount known filesystems as read-write
#     riv util-remount
#   Remount the filesystem containing /foo as read-write
#     riv util-remount /foo

source "${_RIV_SHARE}/riv/lib/stdlib.bash" || exit 1

## Check script dependencies

__require_dependencies findmnt mount

## Set defaults

DIRS=( / /boot )

## Define functions

function parse_options() {
  if [[ "$#" -gt 0 ]]; then
    DIRS=( "$@" )
  fi
}

function remount() {
  local MOUNTS=()

  __say "Remounting read-only filesystems as read/write..."

  for DIR in "${DIRS[@]}"; do
    MOUNTS+=( "$(__find_mount "$DIR")" )
  done

  mapfile -t MOUNTS < <(printf '%s\n' "${MOUNTS[@]}" | sort | uniq)

  for MOUNT in "${MOUNTS[@]}"; do
    if __is_readonly_mount "$MOUNT"; then
      __say "Remouting as read/write: ${MOUNT}..."
      mount "$MOUNT" -o remount,rw
    fi
  done
}

function validate_input() {
  for DIR in "${DIRS[@]}"; do
    test -d "$DIR" || __die "Path does not exist: $DIR"
  done
}

## Run the script

parse_options "$@" &&
validate_input &&
remount
