#!/usr/bin/env bash
#
# Summary: Install system rivian-usb configuration (background service, etc.)
#
# This command is effectively an alias, with `riv self-update`, to provide a
# stable interface for in-place upgrades across versions. For more flexibility,
# see `riv help install`.
#
# Usage: riv self-install

exec riv install -i -t "$_RIV_ROOT"
