#!/usr/bin/env bash
#
# Summary: Display the `riv` version
#
# Usage: riv version [opts]
#        riv --version [opts]
#
# Options:
#   -l Print the longer version

set -e

if [[ "$1" == "-l" ]]; then
  echo -n "Rivian-USB "
  cat "${_RIV_SHARE}/riv/version.txt"
else
  head -1 "${_RIV_SHARE}/riv/version.txt"
fi
