#!/usr/bin/env bash
#
# Summary: List commands and their descriptions
#
# Usage: riv commands
#
# Examples:
#   List commands and summaries:
#     riv commands

set -e

SUMMARIES=1

for arg in "$@"; do
  if [[ "$arg" == "--command-only" ]]; then
    SUMMARIES=
    shift
  fi
done

shopt -s nullglob

{ if [[ -n "$SUMMARIES" ]]; then
    exec riv-help --commands
  else
    for DIR in ${PATH//:/$'\n'}; do
      for CMD in "${DIR}/riv-"*; do
        echo "${CMD##*riv-}"
      done
    done
  fi
} | sort | uniq
