#!/usr/bin/env bash
#
# Summary: List all riv commands
#
# Usage: riv commands
#
# This command is used for autocompletion, and for `riv-help`.

set -e

shopt -s nullglob

{ for path in ${PATH//:/$'\n'}; do
    for command in "${path}/riv-"*; do
      echo "${command##*riv-}"
    done
  done
} | sort | uniq
